### ISSUE TITLE
AI and AF records may show that an A record is a foreign publication

### ISSUE THREAD

**Issue by leonardr** [leonardr/cce-python#2]
Let's say we've got an A record with no renewal. The place of publication doesn't look foreign. Public domain, right?

Except, there's also a renewal for a seemingly unrelated AI or AF record which points to the A record. That indicates the work was _originally_ a foreign publication, and its copyright was automatically restored by treaty.

The A record itself may also say something like "Prev pub. AF12345" -- another indication that it was originally a foreign publication.

**Comment by seanredmond** [comment]
To be accurate, copyright was "restored." Other countries had longer copyright terms and no renewal or need for renewal, so whatever it's copyright status in the US at the time (and it might have been considered public domain), it's copyright was "restored" to match the source country's copyright.

See [Copyright Restoration Under the URAA](https://www.copyright.gov/circs/circ38b.pdf)

**Comment by seanredmond** [comment]
Caveat: there may be _nothing_ in the data to explicitly link the interim or foreign registration to the regular one, and the foreign publication in the AI or AF may have a different title from the US publication!

**Comment by leonardr** [comment]
I implemented this as best I could in https://github.com/leonardr/cce-python/pull/3.
It only makes a difference to six works, and they're all false positives -- none of them actually look like foreign publications and the record number matches look spurious.
So either I'm missing something, or labeling works as foreign by place of publication is extremely effective.

**Comment by seanredmond** [comment]
The interim or foreign registration would have a foreign place of publication, though, while the US pub _would not_. For instance (to take something with an explicit link because it was easy to find) A40320:

    BALDWIN, MONICA. I leap over the wall; contrasts and impressions after twenty-eight years in 
    a convent. New York, Rinehart. 313 p. © Monica Baldwin; 26Jan50; A40320. Appl. states 
    prev. pub. abroad 18Nov49, AI0-210.

This is the US pub (New York), with no renewal. But he interim registration is the UK pub (London): 

    BALDWIN, MONICA. I leap over the wall; a return to the world after twenty-eight years in a
    convent. London, Hamilton. 307 p. illus. © Monica Baldwin; 18Nov49; 2c 16Jan50; AI0-210.

The existence of the UK pub means it's in copyright via restoration even though it wasn't renewed. If I understand correctly how your looking at the place of publication--if "Appl. states prev. pub. abroad 18Nov49, AI0-210" wasn't in the registration so you didn't have the clue about the interim, the fact that A40320 was published in New York and not renewed is still not sufficient to say it's PD.

**Comment by leonardr** [comment]
That's much simpler than what I was doing. In that case, the 'prevPub' mentions that the book was previously published abroad, and the 'prev-regNum' refers to an interim registration. I wasn't looking at those two pieces of data before. It's not necessary to match the specific interim registration, since I'm just trying to filter out books with foreign publications.

Taking prevPub and prev-regNum into account marks 2884 books as foreign that previously weren't known to be foreign, although only 1219 of those books were also lacking a renewal.

**Comment by leonardr** [comment]
To be explicit, what I was doing before (and am still doing) is going through the 'notes' field of the AI and AF records, looking for references to A records. Then if I find any matching A records, I mark them as potentially foreign, because they were mentioned in an AI or AF record. But that matches almost nothing.

**Comment by leonardr** [comment]
So I think what's left is the case where there's an A record, and an AI or AF record, and they're talking about the same book, but neither record mentions the other, and the A record doesn't mention that the book was previously published abroad.

I can probably match a few of these with a title match, but as you mention the title may not match -- especially since the A title may be an English translation of the AI title. So I think we're just about at the limit of what can be done automatically.

Can you show an example of an A/AI registration that looks like this?

**Comment by seanredmond** [comment]
Here's one that spells it out, A19645:

    Coppel, Allec Over the line. [1st American ed.] Garden City, N. Y., Pub. for the Crime Club by 
    Doubleday, 1947. 191 p. 21 ͨͫ. London ed. pub. under title: Man about a dog. © Doubleday
    &amp; Co., inc.; 11Dec47; A19645. ( Pub. abroad 7Nov47; AI-1247)

and AI-1247:

    Cuppel, Alec. A man about a dog. London, G. G. Harrap [1947] 192 p. 10 ͨͫ. © Doubleday 
    &amp; Co., inc., New York; 7Nov47; 1c 12Nov47; AI-1247.

I suspect there are instances where the A registration does not have the link back, and the AI would be hard to connect to it because of the different title.

**Comment by leonardr** [comment]
There are a couple other clues in the text here I could pick up on -- "1st American ed." and "London ed." This particular one would be also okay because of "Pub. abroad". 

If all those clues are missing then there's nothing I can do, and it's not even reasonable to ask you for an example.

**Comment by seanredmond** [comment]
Ultimately, I want to resolve all the references (and add attributes to the XML entries) so we can find the "dangling" AIs and AFs--hopefully few enough to look at manually. Most will be things that were just never published in the US but some will be interim and foreign registrations with harder to find partners.

**Comment by leonardr** [comment]
https://github.com/leonardr/cce-python/pull/4 addresses this as best I can, given the data in the form it is now. The logic for making these decisions is centralized in the `model.py` module.
