### ISSUE TITLE
compare.py cannot handle null renewal regnums

### ISSUE THREAD

**Issue by ghost** [leonardr/cce-python#6]
I'm running Python 2.7. When I run script 2-match-renewals.py I see this error:

```
Traceback (most recent call last):
  File "2-match-renewals.py", line 52, in <module>
    comparator = Comparator("output/1-parsed-renewals.ndjson")
  File "/home/dmeyer/ghcode/cce-python/compare.py", line 15, in __init__
    r = r.replace("-", "")
AttributeError: 'NoneType' object has no attribute 'replace'
```
This appears to be hit wherever there is a `"regnum": null` in output/1-parsed-renewals.ndjson.

It looks like it could be fixed either by ensuring that when there is no regnum in the parsed renewals you put an empty list instead of None; or you could robustify the Comparator init's `for r in regnum` loop to continue if r is None, avoiding the `r = r.replace("-", "")` for a null `r`.

**Comment by ghost** [comment]
I see that cjlee112's [pull request](https://github.com/leonardr/cce-python/pull/5) would fix this issue.

**Comment by leonardr** [comment]
This was fixed by https://github.com/leonardr/cce-python/commit/eefc6f28d14db96634625d171279f59f2fc79b6b
